import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {median,quantile,bins,distribution,summary,comparable,distanceAtTime,groups,finished} from '../docs/assets/analytics.js';
import {sexHistogram,finishPlaceScatter} from '../docs/assets/charts.js';
import {adapt} from '../docs/assets/data-adapter.js';
import {urlState,switched,storage,stateURL} from '../docs/assets/app-state.js';
import {DataLoader} from '../docs/assets/data-loader.js';
import {terrainMetrics} from '../docs/assets/map-engine.js';
import {progression,progressionBySex} from '../docs/assets/views.js';
import {plan} from '../docs/assets/race-plan.js';
const read=p=>JSON.parse(fs.readFileSync(new URL('../docs/data/'+p,import.meta.url),'utf8').replace(/^\uFEFF/,''));
const boot=read('bootstrap.json'),history=read('history.json'),doc=k=>read('races/'+k+'.json'),adapter=k=>adapt(doc(k),boot);
test('presentation provides family-specific goal defaults',()=>{assert.deepEqual(Object.fromEntries(Object.entries(boot.presentation).map(([family,p])=>[family,p.default_goal_seconds])),{ultra60:27000,trail22:9000,trail14:5400,trail5:2100,duo60:23400});});
test('history aggregate carries structural, sex and comparable-record fields',()=>{const e=history.editions.find(x=>x.race_key==='ost-2025-ultra60');assert.ok(e.starters>=e.finished);assert.equal(e.women+e.men,e.sex_coverage);assert.equal(e.women_starters+e.men_starters,e.starter_sex_coverage);assert.ok('women_median' in e&&'men_median' in e);assert.ok(e.best_name);});
test('terrain metrics preserve ascent/descent semantics and reject incomplete elevation',()=>{assert.deepEqual(terrainMetrics([[0,10],[1,30],[2,20],[3,50]]),{ascent:50,descent:10,min:10,max:50,distance:3,coverage:1});assert.equal(terrainMetrics([[0,null],[1,20]]),null);assert.equal(terrainMetrics([[0,10],[1,null],[2,20],[3,30]]),null);});
test('finish histogram exposes total, women and men with text legends',()=>{const html=sexHistogram([{sex:'F',finish_seconds:100},{sex:'M',finish_seconds:110},{sex:'F',finish_seconds:120}],60);assert.match(html,/Totalt/);assert.match(html,/Kvinnor/);assert.match(html,/Män/);assert.match(html,/bar-female/);assert.match(html,/bar-male/);assert.match(html,/data-series-toggle="female"/);assert.match(html,/data-series="female"/);});
test('percentile view exposes per-series sample counts and accessible series toggles',()=>{const html=progressionBySex([{sex:'F',status:'FINISHED',finish_seconds:100},{sex:'F',status:'FINISHED',finish_seconds:200},{sex:'M',status:'FINISHED',finish_seconds:150}],true);assert.match(html,/data-series-toggle="female"/);assert.match(html,/data-series-toggle="male"/);assert.match(html,/Kvinnor · n=2/);assert.match(html,/Män · n=1/);});
test('history aggregate matches every generated race bundle',()=>{
 for(const e of history.editions){
  const d=doc(e.race_key),records=d.race.records,finish=records.filter(finished).map(r=>r.finish_seconds),starters=records.filter(r=>['FINISHED','DNF','DSQ'].includes(r.status));
  const known=records.filter(r=>r.sex==='F'||r.sex==='M'),starterKnown=starters.filter(r=>r.sex==='F'||r.sex==='M');
  assert.equal(e.records,records.length,e.race_key+' records');
  assert.equal(e.starters,starters.length,e.race_key+' starters');
  assert.equal(e.finished,finish.length,e.race_key+' finishers');
  assert.equal(e.dnf,records.filter(r=>r.status==='DNF').length,e.race_key+' DNF');
  assert.equal(e.dns,records.filter(r=>r.status==='DNS').length,e.race_key+' DNS');
  assert.equal(e.dsq,records.filter(r=>r.status==='DSQ').length,e.race_key+' DSQ');
  assert.equal(e.unknown,records.filter(r=>r.status==='UNKNOWN').length,e.race_key+' UNKNOWN');
  assert.equal(e.median,finish.length>=5?median(finish):null,e.race_key+' median');
  assert.equal(e.best,finish.length?Math.min(...finish):null,e.race_key+' best');
  assert.equal(e.sex_coverage,known.length,e.race_key+' sex coverage');
  assert.equal(e.women,known.filter(r=>r.sex==='F').length,e.race_key+' women');
  assert.equal(e.men,known.filter(r=>r.sex==='M').length,e.race_key+' men');
  assert.equal(e.starter_sex_coverage,starterKnown.length,e.race_key+' starter sex coverage');
  assert.equal(e.women_starters,starterKnown.filter(r=>r.sex==='F').length,e.race_key+' women starters');
  assert.equal(e.men_starters,starterKnown.filter(r=>r.sex==='M').length,e.race_key+' men starters');
 }
});
test('finish-place scatter is interactive and preserves sex labels',()=>{const html=finishPlaceScatter([{source_result_id:'1',name:'A',status:'FINISHED',finish_seconds:3600,overall_place:1,sex:'F'},{source_result_id:'2',name:'B',status:'FINISHED',finish_seconds:3900,overall_place:2,sex:'M'},{source_result_id:'3',name:'C',status:'FINISHED',finish_seconds:4200,overall_place:3,sex:null}]);assert.match(html,/data-result="1"/);assert.match(html,/point-female/);assert.match(html,/point-male/);assert.match(html,/point-total/);assert.match(html,/Kvinnor/);assert.match(html,/Män/);});
test('null never becomes zero; interpolated quantiles; fixed bins',()=>{assert.equal(median([null,'',undefined,10,20]),15);assert.equal(quantile([0,10,20,30],.25),7.5);assert.equal(median([]),null);assert.deepEqual(bins([null,900,1799,1800],900).map(b=>b.count),[2,1]);assert.throws(()=>bins([1],0));});
test('percentile ladder respects small-sample publication thresholds',()=>{const rows=n=>Array.from({length:n},(_,i)=>({finish_seconds:1000+i*10}));assert.equal((progression(rows(5)).match(/<strong>–<\/strong>/g)||[]).length,4);assert.equal((progression(rows(10)).match(/<strong>–<\/strong>/g)||[]).length,2);assert.equal((progression(rows(20)).match(/<strong>–<\/strong>/g)||[]).length,0);});
test('small-sample thresholds',()=>{for(let n=0;n<=20;n++){const d=distribution(Array.from({length:n},(_,i)=>i+1));assert.equal(d.median!==null,n>=5);assert.equal(d.q25!==null,n>=10);assert.equal(d.q10!==null,n>=20);}});
test('summary median is withheld below five finishers',()=>{const rows=n=>Array.from({length:n},(_,i)=>({status:'FINISHED',finish_seconds:1000+i*10}));assert.equal(summary(rows(4)).median,null);assert.equal(summary(rows(5)).median,1020);});
test('status counts exclude DNS and unknown starts',()=>{const s=summary([{status:'DNS'},{status:'UNKNOWN'},{status:'DNF'},{status:'FINISHED',finish_seconds:4}]);assert.equal(s.starters,2);assert.equal(s.finished,1);assert.equal(s.dnf,1);});
test('source totals and capability matrix',()=>{let count=0,splits=0,teams=0,members=0,replay=0;for(const key of Object.keys(boot.race_catalog)){const d=doc(key);count+=d.race.records.length;splits+=d.splits.length;teams+=d.teams.length;members+=d.team_members.length;replay+=Number(d.race.capabilities.replay);assert.equal(d.payload_sha256,boot.payload_sha256);assert.ok(d.race.records.every(r=>r.person_key===null));}assert.deepEqual([count,splits,teams,members,replay],[9871,6123,300,599,6]);});
test('2019 semantic checkpoint order is chronological in browser data',()=>{for(const key of ['ost-2019-ultra60','ost-2019-duo60']){const a=adapter(key);assert.deepEqual(a.boundary.map(c=>c.key),['start','stenshuvud','bengtemolla','vantalangan','finish']);const complete=a.records.find(r=>finished(r)&&a.boundary.slice(1).every((_,i)=>a.segment(r,i)));assert.ok(complete,key+' should retain a complete chronological segment journey');}});
test('older ultra split analysis without route; separate 2023 observations',()=>{const old=adapter('ost-2018-ultra60');assert.ok(old.race.capabilities.segment_analysis);assert.equal(old.race.capabilities.replay,false);assert.ok(!old.course.assets.route);const a=adapter('ost-2023-ultra60');assert.ok(a.checkpoints.some(c=>c.key==='bengtemolla_approach'));assert.ok(!a.boundary.some(c=>c.key==='bengtemolla_approach'));assert.ok(a.boundary.some(c=>c.key==='bengtemolla'));assert.ok(a.segmentStats(a.records).some(s=>s.time.n>=20));assert.ok(a.segmentStats(a.records).every(s=>s.median===null));});
test('source placeholder names are preserved as provenance but never shown literally',()=>{const a=adapter('ost-2023-duo60'),r=a.records.find(x=>x.source_name==='undefined');assert.ok(r);assert.equal(r.name,'Lag #2022');assert.equal(r.source_name,'undefined');});
test('Duo membership keeps source order without legs',()=>{const a=adapter('ost-2025-duo60');assert.equal(a.race.participant.entity,'team');assert.equal(a.race.competition.team_structure.member_assignment,'unknown');const m=a.members(a.records[0]);assert.ok(m.length);assert.ok(m.every(x=>x.leg_no===null));assert.deepEqual(m.map(x=>x.source_sequence),m.map(x=>x.source_sequence).sort((a,b)=>a-b));});
test('finish-only and provisional reference do not acquire replay',()=>{for(const family of ['trail22','trail14','trail5']){const a=adapter('ost-2026-'+family);assert.equal(a.race.capabilities.replay,false);assert.equal(a.race.capabilities.segment_analysis,false);}assert.ok(!adapter('ost-2026-trail14').course.assets.route);assert.equal(adapter('ost-2026-trail5').course.assets.official_gpx,false);});
test('missing demographics stay missing and category never creates age',()=>{assert.ok(adapter('ost-2018-ultra60').records.every(r=>r.sex===null));assert.ok(adapter('ost-2022-ultra60').records.some(r=>r.age_category&&r.age===null));});
test('comparison needs evidence, not family alone',()=>{const a=adapter('ost-2025-ultra60').race,b=adapter('ost-2026-ultra60').race;assert.equal(comparable(a,b,boot.courses),true);assert.equal(comparable(a,adapter('ost-2024-ultra60').race,boot.courses),false);assert.equal(comparable(adapter('ost-2018-trail22').race,adapter('ost-2019-trail22').race,boot.courses),false);});
test('DNF stops at final observed anchor and never finishes',()=>{const a=adapter('ost-2025-ultra60'),route=read('courses/'+a.race.course_version+'/route.json'),r=a.records.find(r=>r.status==='DNF'&&a.passages(r).length);assert.ok(r);assert.equal(a.observation(r,'finish'),null);const anchors=a.anchors(r,route);assert.equal(distanceAtTime(anchors,1e9),anchors.at(-1).distance);assert.ok(anchors.at(-1).distance<route.full_distance_km);assert.equal(distanceAtTime([],0),null);});
test('state URLs round trip, hash anchors win and race switch resets dependent choices',()=>{const s={raceKey:'ost-2025-ultra60',section:'compare',profile:'123',compare:['1','2']},url=stateURL('https://example.test/',s);assert.equal(url.hash,'#compare');assert.deepEqual(urlState(url,boot.race_catalog,boot.default_race),s);assert.equal(urlState('https://example.test/?race=ost-2025-ultra60&section=overview#segments',boot.race_catalog,boot.default_race).section,'segments');const next=switched({...s,query:'old',filters:{sex:'F'}},'ost-2026-trail5');assert.deepEqual(next.compare,[]);assert.deepEqual(next.filters,{});assert.equal(next.profile,null);assert.equal(next.query,'');});
test('corrupt storage is safe',()=>{const s=storage('ost',{getItem(){return '{broken';},setItem(){throw Error();}});assert.deepEqual(s.read('favorites',[]),[]);assert.doesNotThrow(()=>s.write('unit','pace'));});
test('loader refuses mixed generation and never requests unknown route',async()=>{const paths=[],l=new DataLoader('',async path=>{paths.push(path);return {ok:true,json:async()=>path==='bootstrap.json'?boot:{payload_sha256:'bad'}};});await l.bootstrap();await assert.rejects(l.race('ost-2025-ultra60'),/uppdaterats/);await assert.rejects(l.route(adapter('ost-2018-ultra60').race),/saknas/);assert.equal(paths.length,2);});
test('plans use complete current-edition observations; no split plan for sparse race',()=>{const a=adapter('ost-2025-ultra60'),p=plan(a,25000);assert.equal(p.method,'observed');assert.ok(Math.abs(p.segments.reduce((sum,s)=>sum+s.seconds,0)-25000)<1e-6);assert.equal(plan(adapter('ost-2026-trail5'),1800).segments.length,0);});
test('case-only clubs group together and n threshold applies',()=>{const g=groups([{club:' Test ',status:'FINISHED',finish_seconds:100},{club:'test',status:'FINISHED',finish_seconds:120}],'club');assert.equal(g.length,1);assert.equal(g[0].median,null);});

